### ISSUE TITLE
wp secure all and PHP Parse error

### ISSUE THREAD

**Issue by fschmittlein** [igorhrcek/wp-cli-secure-command#37]
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /.wp-cli/packages/vendor/igor/wp_cli_secure_command/src/SubCommands/SubCommand.php on line 109

PHP 7.4.28
WP-CLI 2.6.0

**Comment by DanielRuf** [comment]
That's due to the usage of types for parameter and return values which are a new feature in PHP 8.

https://github.com/igorhrcek/wp-cli-secure-command/blob/master/src/SubCommands/SubCommand.php#L109

Please try to change it from

`protected function setRuleContent( bool $loadVars = true, bool|string $template = false ) : string|array {`

to

`protected function setRuleContent( $loadVars = true, $template = false ) {`

Ideally the developers should create some CI / CD with linting (PHP-CLI has linting built-in) and maybe phan or phpstan.

**Comment by DanielRuf** [comment]
Looks like the code was not tested on PHP 7.4. There are many more files which need the proper changes:

https://github.com/wp-cli-secure/wp-cli-secure-command/runs/5798874722?check_suite_focus=true

**Comment by DanielRuf** [comment]
Someone was a bit too enthusiastic to apply PHP 8 syntax to a PHP 7 project:

https://github.com/igorhrcek/wp-cli-secure-command/blob/master/composer.json#L13

So no one with PHP 7 can really use it with the current code.
